config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'
  get 'works', to: 'pages#works'
  get 'contacts', to: 'pages#contacts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created with <%= link_to 'Ruby on Rails', "https://rubyonrails.org/", target: '_blank'%>
    and <%= link_to 'Bootstrap', "https://getbootstrap.com/", target: '_blank'%>.
  </small>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand nav-btn', id: 'home' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'My works', works_path, class: 'navbar-brand nav-btn' %>
        </li>
        <li>
          <%= link_to 'About me', about_path, class: 'navbar-brand nav-btn' %>
        </li>
        <li>
          <%= link_to 'Contacts', contacts_path, class: 'navbar-brand nav-btn' %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>gregoryawesoman</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron about">
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <div class="img-container">
        <%=image_tag('avatar.png', alt: 'my_photo.png', class: 'img-responsive img-custom') %>
      </div>
    </div>
    <div class="description col-md-6 col-xs-12">
      <h1>Igor Lukashin</h1>
      <br>
      <p>QA automation engineer since May, 2018.</p>
      <p>
        Junior developer.<br> Studying Ruby (with Ruby on Rails), Java (Spring), Swift.<br>
        Interested in webapp development, iOS/OSx.
        <%= link_to "JetBrains", "https://www.jetbrains.com/", target: '_blank' %> user.
      </p>
      <br>
      <p><%= link_to 'Write me', contacts_path %> if you need more additional information.</p>
    </div>
  </div>
</div>

app/views/pages/contacts.html.erb
<h1>Contacts:</h1>
<p>Email: <%= mail_to 'gregoryawesoman@icloud.com', 'gregoryawesoman@icloud.com' %></p>
<p>Telegram: <%= link_to '@gregoryawesoman', 'https://tele.click/gregoryawesoman', target: '_blank' %></p>
<small>You can also find me in socials:</small>
<p><%= link_to image_tag('facebook.png'), "https://www.facebook.com/gregoryawesoman", target: '_blank' %>
   <%= link_to image_tag('instagram.png'), "https://www.instagram.com/gregoryawesoman/", target: '_blank'%></p>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome!</h1>
    <br>
    <p class="top-mrg">Hello! This is my official page.</p>
    <p>You can get some information about me and my works here.</p>
    <p>If you interested in or have any questions, you can <%= link_to 'ask me', contacts_path %>.</p>
</div>

app/views/pages/works.html.erb
<h1>Oops, it seems there's still no any works.</h1>
<h1>Try to visit this page later ;)</h1>